-- -- This file contains an example of a sys setting file
--
-- -- Macbook air 13 Sequoia
--
-- return {
--   homebrew_cellar = "/opt/homebrew/Cellar",
--   jdt = {
--     jar = "/opt/homebrew/Cellar/jdtls/1.9.0/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
--     configuration = "/opt/homebrew/Cellar/jdtls/1.9.0/config_mac",
--     bin = "/opt/homebrew/Cellar/jdtls/1.37.0/libexec/bin/jdtls"
--   },
--
-- }
